### ISSUE TITLE
BetterSongList in Namespace

### ISSUE THREAD

**Issue by kinsi55** [nanikit/BetterSort#1]
Would you mind removing BetterSongList from the namespace of this sorter?

My concern is that whenever there happens to be an update which might break this sorter people could be mislead by the logged exceptions, thinking it is related to BetterSongList itself when it might just be the Sorter that broke.

An alternative I'd have in mind could be LastPlayedSort_for_BetterSongList

**Comment by nanikit** [comment]
That makes sense. Thank you for suggestion.

**Comment by nanikit** [comment]
I'm considering `BetterSort.LastPlayed` as a new name. Do you have any concern?

**Comment by kinsi55** [comment]
Maybe BSLSorter?

**Comment by nanikit** [comment]
I want the assembly name is close in alphabetical order at least. I intended indication of dependency. If there's no critical issue for the current candidate (BetterSort.LastPlayed), I want to stick to this.

**Comment by kinsi55** [comment]
I think bettersort is further away than bslsorter - I personally would rather connect the last one to being what it is than the first one, but at the end of the day it is ofc your decision - both options are generally fine

**Comment by nanikit** [comment]
Close by 587ed81294599a10893c681629f79e4c0787ded8.
